Concuerror 0.17 ('3dfce9e') started at 01 May 2017 18:23:44
 Options:
  [{after_timeout,1000},
   {assertions_only,false},
   {assume_racing,true},
   {depth_bound,500},
   {disable_sleep_sets,false},
   {dpor,optimal},
   {entry_point,{'Elixir.SpawnReg.ConcurrencyTest',test,[]}},
   {ignore_error,[]},
   {instant_delivery,true},
   {interleaving_bound,infinity},
   {keep_going,false},
   {non_racing_system,[]},
   {pa,"/Users/i335774/Documents/Elixir/learning-elixir/Chapter 11/concuerror_playground/_build/test/lib/concuerror_playground/ebin/"},
   {print_depth,20},
   {scheduling,round_robin},
   {scheduling_bound_type,none},
   {show_races,true},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,1000},
   {treat_as_normal,[normal]},
   {use_receive_patterns,false}]
################################################################################
Interleaving #1
--------------------------------------------------------------------------------
Errors found:
* At step 3 process P exited abnormally
    Reason:
      {badarg,[{erlang,send,
                       ['Elixir.SpawnReg',stop],
                       [7,{file,"test/concurrency/spawn_reg_test.ex"}]}]}
    Stacktrace:
      [{erlang,send,
               ['Elixir.SpawnReg',stop],
               [7,{file,"test/concurrency/spawn_reg_test.ex"}]}]
* Blocked at a 'receive' (when all other processes have exited):
    P.1.1 in SpawnReg.ex line 16
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<'Elixir.SpawnReg.ConcurrencyTest'.'-test/0-fun-0-'.0>,[]])
    in erlang.erl line 2626
   2: P: Exception badarg raised by: erlang:send('Elixir.SpawnReg', stop)
    in spawn_reg_test.ex line 7
   3: P: exits abnormally ({badarg,[{erlang,send,['Elixir.SpawnReg',stop],[7,{file,[116,101,115,116,47,99,111,110|...]}]}]})
   4: P.1: undefined = erlang:whereis('Elixir.SpawnReg')
    in process.ex line 463
   5: P.1: P.1.1 = erlang:spawn(erlang, apply, [#Fun<'Elixir.SpawnReg'.'-start/0-fun-0-'.0>,[]])
    in erlang.erl line 2626
   6: P.1: true = erlang:register('Elixir.SpawnReg', P.1.1)
    in process.ex line 428
   7: P.1: exits normally
--------------------------------------------------------------------------------
New races found:
*    2: P: Exception badarg raised by: erlang:send('Elixir.SpawnReg', stop)
     6: P.1: true = erlang:register('Elixir.SpawnReg', P.1.1)


################################################################################
Exploration completed!
################################################################################
Errors:
--------------------------------------------------------------------------------
Stop testing on first error. (Check '-h keep_going').

################################################################################
Warnings:
--------------------------------------------------------------------------------
Multiple instances of '--pa' defined. Using last value: "/Users/i335774/Documents/Elixir/learning-elixir/Chapter 11/concuerror_playground/_build/test/lib/concuerror_playground/ebin/".
Multiple instances of '--pa' defined. Using last value: "/Users/i335774/Documents/Elixir/learning-elixir/Chapter 11/concuerror_playground/_build/test/lib/concuerror_playground/ebin/".

################################################################################
Info:
--------------------------------------------------------------------------------
Instrumented io_lib
Instrumented gen_server
Instrumented 'Elixir.SpawnReg.ConcurrencyTest'
Instrumented erlang
Instrumented 'Elixir.SpawnReg'
Instrumented 'Elixir.Process'

################################################################################
Done at 01 May 2017 18:23:44 (Exit status: error)
  Summary: 1 errors, 1/2 interleavings explored
